### ISSUE TITLE
MQTT status "disconnected" not updated when ethernet is down

### ISSUE THREAD

**Issue by moinmoin-sh** [SuperHouse/OXRS-SHA-Rack32-ESP32-LIB#7]
When pulling the ethernet cable after the successful boot the IP-link status is updated properly, but the MQTT led's stay grey - not showing red as supposed. About 1 min after disconnecting "FAILOVER" is shown on serial and MQTT rx/tx leds stop blinking, but don't show red.

**Comment by sumnerboy12** [comment]
Yeah I knew about this - and had a look at trying to resolve it - but the PubSubClient doesn't notice the connection is down until a keep alive ping fails, And because we no longer call `_mqtt.loop()` if the ethernet link is down we never send/check the ping results.

I kind of thought that if IP is down, it is enough to show the red LED and `---.---.---.---` on the LCD. The MQTT LEDs are only interesting if the IP link is UP. If the link is UP but we can't connect to the broker, you will see the two red LEDs.

Otherwise we can't leave the MQTT connection state detection to the MQTT lib (which is ideally where it should be). We have to check the ethernet link and manually set the MQTT connection state etc.

**Comment by sumnerboy12** [comment]
I am not sure. I recently made a few changes since the MQTT topic display was not being updated if the user changed the client id or topic prefix/suffix on-the-fly. So now the Rack32 lib sets the connection status AND the display topic on MQTT connect/disconnect events. On startup it displays an empty topic which I think looks quite nice - you don't see the topic on the LCD until there is a connection attempt.

I kind of like the way it works now. You only see the red LEDs if there is an ethernet link but the broker connection failed - i.e. the broker is down or your creds are wrong. To me that is obvious the problem is with your MQTT broker/config. If the IP LED is red, then the problem is with your LAN/cable etc. Having both red when you pull the plug is a little redundant IMO?

In saying that - moving some of this logic to the LCD library probably makes sense. It would mean passing our OXRS MQTT pointer, rather than PubSubClient, so that you can retrieve `mqtt.getWildcardTopic()` to update the display on connection state change. This would also need a `boolean connected()` public method added to our MQTT library so it can check the state.

I think it is worth doing but am quite keen to keep the current functionality - would you agree? Have you seen my recent changes and tested them locally?

**Comment by moinmoin-sh** [comment]
That's ok. We can leave it if you like it as it is.
I saw that you made some changes but haven't tested it so far.

**Comment by sumnerboy12** [comment]
You have got me thinking tho - I might have a play with it...
